# Root BUILD
# config_setting for environment (used by child packages if needed)
package(default_visibility = ["//visibility:public"])

config_setting(
    name  = "is_prod",
    define_values = {"build_env": "prod"},
)

config_setting(
    name  = "is_dev",
    define_values = {"build_env": "dev"},
)
