apiVersion: v1
kind: PersistentVolume
metadata:
  name: mysql-pv-jegan          # Replace 'jegan' with your name
  labels:
    app: mysql
spec:
  capacity:
    storage: 2Gi                # Shared across all MySQL instances (3 x ~500Mi each)
  volumeMode: Filesystem
  accessModes:
  - ReadWriteMany               # Required so mysql-0, mysql-1, mysql-2 can all mount this
  persistentVolumeReclaimPolicy: Retain
  nfs:
    server: 192.168.10.200      # Replace with 192.168.10.201 if you're working on second server
    path: /var/nfs/jegan/mysql  # Replace jegan with your linux user
