apiVersion: v1
kind: PersistentVolume
metadata:
  name: wordpress-pv-jegan           # Replace 'jegan' with your name
  labels:
    app: wordpress
spec:
  capacity:
    storage: 500Mi
  volumeMode: Filesystem
  accessModes:
  - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain
  nfs:
    server: 192.168.10.200          # Replace this IP with 192.168.10.201 if you're working on second server
    path: /var/nfs/jegan/wordpress  # Replace jegan with your linux user
